### ISSUE TITLE
Unused dependencies?

### ISSUE THREAD

**Issue by lambdagolem** [http-rs/async-session#28]
The sha2 and hmac dependencies look unused to me. Is there a reason for these dependencies?

**Comment by jbr** [comment]
This crate is intended to be used by server frameworks, and the server frameworks use those reexports, like this https://github.com/http-rs/tide/blob/main/src/sessions/middleware.rs#L9-L13

**Comment by lambdagolem** [comment]
Thank you for your response. Is there a particular reason that these server frameworks don't directly depend on the crates and use them as reexports?

**Comment by jbr** [comment]
The intent was that it simplifies [the feature logic](https://github.com/http-rs/tide/blob/main/Cargo.toml#L32 in the framework cargo.toml): Instead of toggling on and off a set of different crates, the async-session crate would provide everything needed to implement sessions. I couldn't think of any situation in which someone should be depending on async-session without also needing sha2 and hmac, either directly or through the cookie crate

**Comment by lambdagolem** [comment]
Thank you for your explanation!
