### ISSUE TITLE
MemoryStore not valid for production usage

### ISSUE THREAD

**Issue by FlakM** [http-rs/async-session#30]
Welcome!

I've recently gotten an opportunity to do first pet project in rust and decided on using axum which gives an example of using async-session:

```rust
    // `MemoryStore` is just used as an example. Don't use this in production.
    let store = MemoryStore::new();
```
https://github.com/tokio-rs/axum/blob/main/examples/oauth/src/main.rs#L42

The same warning is memory store itself

https://github.com/http-rs/async-session/blob/93a11ae4042df127cb2465ea46106d59fee7f699/src/memory_store.rs#L10

Is there a reason why this should not be used in production if losing all sessions on application crash acceptable behavior and application is not clustered? If there is I would love to add it in documentation in pointed places for others to understand.

Also many kudos for your work! :1st_place_medal:

**Comment by jbr** [comment]
The primary concern is that someone new to web stuff would use the memory store because it takes the least configuration, but then be confused when everyone gets logged out on server restart (or similar). If the cleanup task is run intermittently, you don't mind losing sessions on restart, and there aren't too many active sessions to fit in memory there is no reason the memory store would be a poor choice. Docs PRs clarifying that would be welcome as long as someone new to web sessions wouldn't accidentally deploy it and be surprised about those constraints.

**Comment by FlakM** [comment]
I've written down my thoughts using some terms that someone new to web stuff should easily google like load balancing or ssl termination. Also I've duplicated some of the links from main README.md as it leaves someone with actionable alternatives.
