### ISSUE TITLE
Replace chrono

### ISSUE THREAD

**Issue by dignifiedquire** [http-rs/async-session#32]
Unfortunately chrono is still unpatched for a security advisory: https://github.com/chronotope/chrono/issues/499 so it would be good to replace it, as this starts triggering folks from removing tide.

**Comment by dignifiedquire** [comment]
Brave is removing chrono for similar reasons: https://github.com/brave/brave-browser/issues/20568

**Comment by yoshuawuyts** [comment]
Oh, that's really annoying. It seems brave moved off `chrono` and onto` time` [here]( https://github.com/brave/brave-core/pull/10965/files#diff-3417003287ee754f17d419041ea27f98e888e796f3cb16524ee479f4e932a3bfR20). If you want to perform the move, I don't have objections. Though I do hope that the latest rust-sec response will motivate folks to patch `chrono`, since it's a core crate in the Rust ecosystem.

**Comment by dignifiedquire** [comment]
Doesn't look like there is much hope of it getting resolved reading this: https://github.com/chronotope/chrono/pull/639

**Comment by daviessm** [comment]
Chrono now has a new maintainer with new releases imminent.
